//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace CompanyManagement.Models
{
    public partial class Company
    {
        public Company()
        {
            this.Companies1 = new HashSet<Company>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string NodeName { get; set; }
        public int Earnings { get; set; }
    
        public virtual ICollection<Company> Companies1 { get; set; }
        public virtual Company Company1 { get; set; }
    }
    
}
